#!/bin/sh

artist="`/usr/bin/mpc --format '%artist%' | head -n 1 | tr -d '\n'`";
title="`/usr/bin/mpc --format '%title%' | head -n 1 | tr -d '\n'`";

groupTitle="$artist - $title"

#echo $groupTitle

#cat "/Users/jgerold/.lyrics/$groupTitle.txt"

if [[ -f "/home/fsk141/.lyrics/$groupTitle.txt" ]]; then
	/bin/cat "/home/fsk141/.lyrics/$groupTitle.txt"
else
	/usr/bin/perl /home/fsk141/.scripts/02-from-lyrics-wikia-com.pl
	/bin/cat "/home/fsk141/.lyrics/$groupTitle.txt"
fi
