#!/bin/bash

#################################################
#           Calvin & Hobbes APOD                #
#           Version 1                           #
#################################################

#///////////////////////////////////////////////#
#    Author: Jonny Gerold <jonny@fsk141.com>    #
#///////////////////////////////////////////////#

#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Storage Directory
SDIR="$HOME/.chapod"

# Screen Resolution
RESOLUTION="1280x800"

URL="http://apod.nasa.gov/apod/"
IMAGEPATH=`curl $URL 2>/dev/null | grep IMG | cut -d\" -f2`
RAWCH="http://dl.dropbox.com/u/52078/chblank.png"
APOD="$URL${IMAGEPATH%.jpg}`echo "_big.jpg"`"
OS=`uname -s`

# Make SDIR
if [[ ! -d $SDIR ]]; then
	mkdir $SDIR
fi

# Get the raw Calvin & Hobbes image
if [[ ! -e $SDIR/chblank.png ]]; then
	curl $RAWCH -o $SDIR/chblank.png 2>/dev/null
fi

# Get the apod
if [[ -e $SDIR/apod.jpg ]]; then
	rm $SDIR/apod.jpg
fi
curl $APOD -o $SDIR/apod.jpg 2>/dev/null

# Resize raw C&H image & apod
for image in apod.jpg chblank.png
	do convert $SDIR/$image -background transparent -resize $RESOLUTION^ -gravity south -extent $RESOLUTION $SDIR/tmp.$image
done

# Lets join them together
convert $SDIR/{tmp.apod.jpg,tmp.chblank.png} -mosaic $SDIR/chapod.jpg
rm $SDIR/tmp.*

# Now lets set the background
if [[ $OS == "Darwin" ]]; then
	defaults write com.apple.Desktop Background "{default = {ChangePath = "$HOME/Pictures/Wallpapers"; ChooseFolderPath = "$HOME/Pictures/Wallpapers"; CollectionString = Wallpapers; ImageFileAlias = <00000000 00e00003 00000000 c2cc314a 0000482b 00000000 00089e0c 001be568 0000c2fe 8ab30000 00000920 fffe0000 00000000 0000ffff ffff0001 00100008 9e0c0007 4cea0007 4cb40013 52b2000e 00260012 00740068 00650065 006d0070 00690072 0065005f 00310036 00380030 002e006a 00700067 000f001a 000c004d 00610063 0069006e 0074006f 00730068 00200048 00440012 00355573 6572732f 6b726963 68617264 2f506963 74757265 732f5761 6c6c7061 70657273 2f746865 656d7069 72655f31 3638302e 6a706700 00130001 2f000015 0002000f ffff0000 >; ImageFilePath = "$SDIR/chapod.jpg"; Placement = Crop; TimerPopUpTag = 6; };}"
	killall Dock
else
	feh --bg-scale $SDIR/chapod.jpg &
fi
