#!/bin/bash

#################################################
#           Calvin & Hobbes APOD                #
#           Version 1.awesome                   #
#################################################

#///////////////////////////////////////////////#
#    Author: Jonny Gerold <jonny@fsk141.com>    #
#///////////////////////////////////////////////#

#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Storage Directory
SDIR="$HOME/.chapod"

# Screen Resolution
RESOLUTION="1920x1200"

# Raw Calvin & Hobbes foreground
RAWCH="http://dl.dropbox.com/u/52078/chblank.png"

# Base URL for apod
BURL="http://apod.nasa.gov/apod/"

# OS Check
OS=`uname -s`

# If a url is specified use that, otherwise use apod
if [[ -n "$1" ]]; then

	# Entered URL
	EURL="$1"
	IMAGEPATH=`curl $EURL 2>/dev/null | grep 'href="image' | cut -d\" -f2`
	APOD="$BURL$IMAGEPATH"
else
	IMAGEPATH=`curl $BURL 2>/dev/null | grep 'href="image' | cut -d\" -f2`
	APOD="$BURL$IMAGEPATH"
fi

# Make SDIR
if [[ ! -d $SDIR ]]; then
	mkdir $SDIR
fi

# Get the raw Calvin & Hobbes image
if [[ ! -e $SDIR/chblank.png ]]; then
	curl $RAWCH -o $SDIR/chblank.png 2>/dev/null
fi

# Get the apod
if [[ -e $SDIR/apod.jpg ]]; then
	rm $SDIR/apod.jpg
fi
curl $APOD -o $SDIR/apod.jpg 2>/dev/null

# Resize raw C&H image & apod
for image in apod.jpg chblank.png
	do /opt/local/bin/convert $SDIR/$image -background transparent -resize $RESOLUTION^ -gravity south -extent $RESOLUTION $SDIR/tmp.$image
done

# Lets join them together
if [[ -e $SDIR/chapod.jpg ]]; then 
	rm $SDIR/chapod.jpg
	CHA="chapod1.jpg"
	/opt/local/bin/convert $SDIR/{tmp.apod.jpg,tmp.chblank.png} -mosaic $SDIR/chapod1.jpg
else
	CHA="chapod.jpg"
	/opt/local/bin/convert $SDIR/{tmp.apod.jpg,tmp.chblank.png} -mosaic $SDIR/chapod.jpg
fi

rm $SDIR/tmp.*

# Now lets set the background
if [[ $OS == "Darwin" ]]; then
	osascript -e "tell application \"System Events\" to set picture of every desktop to \"$SDIR/$CHA\""
else
	feh --bg-scale $SDIR/chapod*.jpg &
fi
