#!/bin/sh
if  [ -f /var/run/dhcpcd-wlan0.pid ]
then

	echo 'Killing dhcpcd'
	sudo dhcpcd wlan0 -k
	echo 'Starting connection to' "$1"
        sudo iwconfig wlan0 mode Managed essid "$1" key $2
	sudo dhcpcd wlan0
	echo 'Connected to' "$1"
	/usr/bin/notify-send 'Connected to' "$1"
else
	echo 'Starting connection to' "$1"
	sudo iwconfig wlan0 mode Managed essid "$1" key $2
	sudo dhcpcd wlan0
	echo 'Connected to' "$1"
	/usr/bin/notify-send 'Connected to' "$1"
fi
