#!/bin/bash

DEFAULT_COVER="defaultcover.png"

#MUSICDIR=`cat /etc/mpd.conf | grep -v "#" | grep music_directory | sed -e 's/"//g'`
MUSICDIR="~/Music"
MUSICDIR=${MUSICDIR:24}
MUSICDIR=${MUSICDIR%/$}

MFILE=`/usr/bin/mpc current -f %file%`
MFILE=${MFILE%/*}
MFILE=${MFILE%/$}

FULLDIR="$MUSICDIR/$MFILE"


COVERS=`ls "$FULLDIR" | grep "\.jpg\|\.png\|\.gif"`

if [ -z "$COVERS" ]; then
	COVERS="$DEFAULT_COVER"
else
	TRYCOVERS=`echo "$COVERS" | grep "cover\|front" | head -n 1`

	if [ -z "$TRYCOVERS" ]; then
		TRYCOVERS=`echo "$COVERS" | head -n 1`
		if [ -z "$TRYCOVERS" ]; then
			TRYCOVERS="$DEFAULT_COVER"
		else
			TRYCOVERS="$FULLDIR/$TRYCOVERS"
		fi
	else
		TRYCOVERS="$FULLDIR/$TRYCOVERS"
	fi

	COVERS="$TRYCOVERS"
fi

echo -n "$COVERS"
cp "$COVERS" ~/.cover.jpg
exit 0
