#!/bin/sh
if  [ -f /var/run/dhcpcd-eth0.pid ]
then
        echo 'Killing dhcpcd'
        sudo dhcpcd eth0 -k
	sudo ifconfig wlan0 down
	sudo ifconfig eth0 up
        echo 'Starting connection to Wired'
        sudo dhcpcd eth0
        echo 'Connected to Wired'
	/usr/bin/notify-send 'Connect to Wired'
else
        echo 'Starting connection to Wired'
	sudo ifconfig wlan0 down
        sudo ifconfig eth0 up
        sudo dhcpcd eth0
        echo 'Connected to Wired'
	/usr/bin/notify-send 'Connect to Wired'
fi
